#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinxcontrib_napoleon
Version  : 0.7
Release  : 8
URL      : https://files.pythonhosted.org/packages/fa/eb/ad89500f4cee83187596e07f43ad561f293e8e6e96996005c3319653b89f/sphinxcontrib-napoleon-0.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/fa/eb/ad89500f4cee83187596e07f43ad561f293e8e6e96996005c3319653b89f/sphinxcontrib-napoleon-0.7.tar.gz
Summary  : Sphinx "napoleon" extension.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-sphinxcontrib_napoleon-license = %{version}-%{release}
Requires: pypi-sphinxcontrib_napoleon-python = %{version}-%{release}
Requires: pypi-sphinxcontrib_napoleon-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(coverage)
BuildRequires : pypi(flake8)
BuildRequires : pypi(mock)
BuildRequires : pypi(nose)
BuildRequires : pypi(pockets)
BuildRequires : pypi(six)
BuildRequires : pypi(sphinx)

%description
===============================================

%package license
Summary: license components for the pypi-sphinxcontrib_napoleon package.
Group: Default

%description license
license components for the pypi-sphinxcontrib_napoleon package.


%package python
Summary: python components for the pypi-sphinxcontrib_napoleon package.
Group: Default
Requires: pypi-sphinxcontrib_napoleon-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinxcontrib_napoleon package.


%package python3
Summary: python3 components for the pypi-sphinxcontrib_napoleon package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_napoleon)
Requires: pypi(pockets)
Requires: pypi(six)

%description python3
python3 components for the pypi-sphinxcontrib_napoleon package.


%prep
%setup -q -n sphinxcontrib-napoleon-0.7
cd %{_builddir}/sphinxcontrib-napoleon-0.7
pushd ..
cp -a sphinxcontrib-napoleon-0.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656409447
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_napoleon
cp %{_builddir}/sphinxcontrib-napoleon-0.7/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_napoleon/b27c016b297ad29fd3e47abea64d506084822690
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinxcontrib_napoleon/b27c016b297ad29fd3e47abea64d506084822690

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
